name: SST-Elements Test Frameworks

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - master
      - devel

defaults:
  run:
    shell: bash -l {0}

jobs:
  Build_and_Test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        python-version: [2.7, 3.6, 3.8]
#        python-version: [2.7, 3.5, 3.6, 3.7, 3.8, 3.9]
    name: Test:${{ matrix.os }}/PY-${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}

    steps:
    - name: System Information Dump - Startup
      run: |
        echo "*******************************************"
        echo "*** SYSTEM INFO DUMP AT STARTUP"
        echo "*******************************************"
        echo
        echo "pwd = " `pwd`
        echo "***"
        echo "env | sort = "
        env | sort
        echo "***"

    - name: Set Source and General Install Env Variables
      run: |
        echo "*******************************************"
        echo "*** SET SOURCE AND LOCAL DIR ENV VAR (THIS AFFECTS FUTURE STEPS)"
        echo "*******************************************"
        echo "SST_SOURCE_PATH=$HOME/work/sst-elements/sst-elements" >> $GITHUB_ENV
        echo "SST_GEN_INSTALL_PATH=$HOME/local" >> $GITHUB_ENV
        echo "***"
        echo "LOCATION OF GITHUB_ENV SCRIPT"
        echo $GITHUB_ENV
        echo "***"
        echo "CONTENTS OF GITHUB_ENV"
        cat $GITHUB_ENV
        echo "***"

    - name: Set SST Core and Elements Install Env Variables
      run: |
        echo "*******************************************"
        echo "*** SET ENV VARS (THIS AFFECTS FUTURE STEPS)"
        echo "*******************************************"
        echo "SST_CORE_SOURCE_PATH=$SST_SOURCE_PATH/sst-core_source" >> $GITHUB_ENV
        echo "SST_ELEMENTS_SOURCE_PATH=$SST_SOURCE_PATH/sst-elements_source" >> $GITHUB_ENV
        echo "SST_CORE_HOME=$SST_GEN_INSTALL_PATH/sstcore_install" >> $GITHUB_ENV
        echo "SST_ELEMENTS_HOME=$SST_GEN_INSTALL_PATH/sstelements_install" >> $GITHUB_ENV
        echo "SST_CORE_BIN=$SST_GEN_INSTALL_PATH/sstcore_install/bin" >> $GITHUB_ENV
        echo "SST_ELEMENTS_BIN=$SST_GEN_INSTALL_PATH/sstelements_install/bin" >> $GITHUB_ENV
        echo "***"
        echo "LOCATION OF GITHUB_ENV SCRIPT"
        echo $GITHUB_ENV
        echo "***"
        echo "CONTENTS OF GITHUB_ENV"
        cat $GITHUB_ENV
        echo "***"

#   Checkout this users SST-Elements repo/branch
    - name: Checkout Users SST-Elements source
      uses: actions/checkout@v2
      with:
        path: ./sst-elements_source

#   Checkout the sstsimulator orgs sst-core/devel branch
    - name: Checkout sstsimulator SST-Core source
      uses: actions/checkout@v2
      with:
        repository: sstsimulator/sst-core
        ref: devel
        path: ./sst-core_source

    - name: Check Source Directories
      run: |
        echo "*******************************************"
        echo "*** CHECK INSTALL DIRS AND SET PATH"
        echo "*******************************************"
        echo "$HOME path = " `echo $HOME`
        echo "$SST_CORE_HOME path = " `echo $SST_CORE_HOME`
        echo "$SST_CORE_BIN path = " `echo $SST_CORE_BIN`
        echo "***"
        echo "ls HOME "
        ls -lia $HOME
        echo "***"
        echo "SST_SOURCE_PATHS = " `echo $SST_SOURCE_PATH`
        echo "ls SST_SOURCE_PATHS "
        ls -lia $SST_SOURCE_PATHS
        echo "***"
        echo "SST_ELEMENTS_SOURCE_PATH = " `echo $SST_ELEMENTS_SOURCE_PATH`
        echo "ls SST_ELEMENTS_SOURCE_PATH "
        ls -lia $SST_ELEMENTS_SOURCE_PATH
        echo "***"
        echo "SST_CORE_SOURCE_PATH = " `echo $SST_CORE_SOURCE_PATH`
        echo "ls SST_CORE_SOURCE_PATH "
        ls -lia $SST_CORE_SOURCE_PATH
        echo "***"

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install TestTools Module
      run: |
        echo "*******************************************"
        echo "*** INSTALL TESTTOOLS"
        echo "*******************************************"
        pip install testtools
        echo "***"

    - name: Install OpenMPI
      run: |
        echo "*******************************************"
        echo "*** INSTALL OPENMPI"
        echo "*******************************************"
        sudo apt-get install -y openmpi-bin
        echo "***"
        echo "Trying mpirun = " `which mpirun`
        echo "mpirun version = " `mpirun --version`
        echo "***"

    - name: Install Autotools
      run: |
        echo "*******************************************"
        echo "*** INSTALL AUTOTOOLS"
        echo "*******************************************"
        echo "Trying to install libtool"
        sudo apt-get install -y libtool-bin
        echo "***"
        echo "LIBTOOLIZE path = " `echo $LIBTOOLIZE`
        echo "LIBTOOL path = " `echo $LIBTOOL`
        echo "LIBTOOLIZE version = " `libtoolize --version`
        echo "LIBTOOL    version = " `libtool --version`
        echo "***"

    - name: System Information Dump - Before Build
      run: |
        echo "*******************************************"
        echo "*** SYSTEM INFO DUMP BEFORE BUILD"
        echo "*******************************************"
        echo
        echo "pwd = " `pwd`
        echo "***"
        echo "env | sort = "
        env | sort
        echo "***"

    - name: Build and Install SST-Core
      run: |
        echo "*******************************************"
        echo "*** CHANGE DIRECTORY TO SST-Core SOURCE DIR"
        echo "*******************************************"
        cd $SST_CORE_SOURCE_PATH
        echo "pwd = " `pwd`
        echo "***"
        echo "*******************************************"
        echo "*** RUNNING AUTOGEN ON SST-Core"
        echo "*******************************************"
        ./autogen.sh
        echo "***"
        echo "*******************************************"
        echo "*** RUNNING CONFIGURE ON SST-Core"
        echo "*******************************************"
        ./configure --prefix=$SST_CORE_HOME
        echo "***"
        echo "*******************************************"
        echo "*** RUNNING MAKE ON SST-Core"
        echo "*******************************************"
        make -j16
        echo "***"
        echo "*******************************************"
        echo "*** RUNNING MAKE INSTALL ON SST-Core"
        echo "*******************************************"
        make install
        echo "***"

    - name: Build and Install SST-Elements
      run: |
        echo "*******************************************"
        echo "*** CHANGE DIRECTORY TO SST-Elements SOURCE DIR"
        echo "*******************************************"
        cd $SST_ELEMENTS_SOURCE_PATH
        echo "pwd = " `pwd`
        echo "***"
        echo "*******************************************"
        echo "*** RUNNING AUTOGEN ON SST-Elements"
        echo "*******************************************"
        ./autogen.sh
        echo "***"
        echo "*******************************************"
        echo "*** RUNNING CONFIGURE ON SST-Elements"
        echo "*******************************************"
        ./configure --prefix=$SST_CORE_HOME --with-sst-core=$SST_CORE_HOME
        echo "***"
        echo "*******************************************"
        echo "*** RUNNING MAKE ON SST-Elements"
        echo "*******************************************"
        make -j16
        echo "***"
        echo "*******************************************"
        echo "*** RUNNING MAKE INSTALL ON SST-Elements"
        echo "*******************************************"
        make install
        echo "***"

    - name: Check Installation Dirs and Set PATH Env Var
      run: |
        echo "*******************************************"
        echo "*** CHECK INSTALL DIRS"
        echo "*******************************************"
        echo "$HOME path = " `echo $HOME`
        echo "$SST_GEN_INSTALL_PATH path = " `echo $SST_GEN_INSTALL_PATH`
        echo "$SST_CORE_HOME path = " `echo $SST_CORE_HOME`
        echo "$SST_ELEMENTS_HOME path = " `echo $SST_CORE_HOME`
        echo "$SST_CORE_BIN path = " `echo $SST_CORE_BIN`
        echo "$SST_ELEMENTS_BIN path = " `echo $SST_ELEMENTS_BIN`
        echo "***"
        echo "ls $HOME "
        ls -lia $HOME
        echo "***"
        echo "ls $HOME/local "
        ls -lia $HOME/local
        echo "***"
        echo "ls $SST_GEN_INSTALL_PATH"
        ls -lia $SST_GEN_INSTALL_PATH
        echo "***"
        echo "ls $SST_CORE_HOME"
        ls -lia $SST_CORE_HOME
        echo "***"
        echo "ls $SST_CORE_BIN"
        ls -lia $SST_CORE_BIN
        echo "***"
        echo "ls $SST_ELEMENTS_HOME"
        ls -lia $SST_ELEMENTS_HOME
        echo "***"
        echo "ls $SST_ELEMENTS_BIN"
        ls -lia $SST_ELEMENTS_BIN
        echo "***"

    - name: Set Path to the SST bin Directory
      run: |
        echo "*******************************************"
        echo "*** SET THE PATH TO SST BIN DIR (ONLY AVAILABLE IN FUTURE STEPS)"
        echo "*******************************************"
        echo $SST_CORE_BIN >> $GITHUB_PATH
        echo "***"
        echo "LOCATION OF GITHUB_PATH SCRIPT"
        echo $GITHUB_PATH
        echo "***"
        echo "CONTENTS OF GITHUB_PATH"
        cat $GITHUB_PATH
        echo "***"

    - name: Quick Check of SST-Core Operation
      run: |
        echo "*******************************************"
        echo "*** QUICK CHECK OF SST-CORE OPERATION"
        echo "*******************************************"
        echo "cd to $HOME"
        cd $HOME
        echo "***"
        echo "RUNNING SST FROM HOME DIR"
        echo "sst version = " `$SST_CORE_BIN/sst --version`
        echo "***"
        echo "RUNNING SST --VERSION USING THE PATH"
        sst --version
        echo "***"

    - name: Perform Frameworks Testing on SST-Core
      run: |
        echo "*******************************************"
        echo "*** FRAMEWORKS TESTING - SST-CORE"
        echo "*******************************************"
        echo "cd to $HOME"
        cd $HOME
        echo "***"
        sst-test-core
        echo "***"

    - name: Perform Frameworks Testing on SST-Elements
      run: |
        echo "*******************************************"
        echo "*** FRAMEWORKS TESTING - SST-ELEMENTS"
        echo "*******************************************"
        echo "cd to $HOME"
        cd $HOME
        echo "***"
        sst-test-elements
        echo "***"

