name: SST-Elements Test Frameworks

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - master
      - devel

defaults:
  run:
    shell: bash -l {0}

jobs:
  Build_and_Test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        python-version: [2.7]
#        python-version: [2.7, 3.5, 3.6, 3.7, 3.8, 3.9]
    name: Test:${{ matrix.os }}/PY-${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}

    steps:
    - name: Set Env Variables
      run: |
        echo "*******************************************"
        echo "*** SET ENV VARIABLES (AFFECTS FUTURE STEPS)"
        echo "*******************************************"
        echo "SST_SOURCE_PATHS=$HOME/work/source" >> $GITHUB_ENV
        echo "SST_CORE_SOURCE_PATH=$HOME/work/source/sstscore" >> $GITHUB_ENV
        echo "SST_ELEMENTS_SOURCE_PATH=$HOME/work/source/sst-elements" >> $GITHUB_ENV
        echo "SST_CORE_HOME=$HOME/local/sstcore_install" >> $GITHUB_ENV
        echo "SST_ELEMENTS_HOME=$HOME/local/sstelements_install" >> $GITHUB_ENV
        echo "SST_CORE_BIN=$HOME/local/sstcore_install/bin" >> $GITHUB_ENV
        echo "SST_ELEMENTS_BIN=$HOME/local/sstelements_install/bin" >> $GITHUB_ENV
        echo "***"
        echo "LOCATION OF GITHUB_ENV SCRIPT"
        echo $GITHUB_ENV
        echo "***"
        echo "CONTENTS OF GITHUB_ENV"
        cat $GITHUB_ENV
        echo "***"

    - name: Checkout SST-Elements source
      uses: actions/checkout@v2
      with:
        path: ./sst-elements_source

    - name: Checkout SST-Core source
      uses: actions/checkout@v2
      with:
        repository: sstsimulator/sst-core
        path: ./sst-core_source

#    - name: Set up Python ${{ matrix.python-version }}
#      uses: actions/setup-python@v2
#      with:
#        python-version: ${{ matrix.python-version }}

    - name: System Information Dump - Startup
      run: |
        echo "*******************************************"
        echo "*** SYSTEM INFO DUMP AT STARTUP"
        echo "*******************************************"
        echo
        echo "pwd = " `pwd`
        echo "***"
        echo "env | sort = "
        env | sort
        echo "***"

    - name: DEBUG - Check SOURCE DIRS
      run: |
        echo "*******************************************"
        echo "*** CHECK INSTALL DIRS AND SET PATH"
        echo "*******************************************"
        echo "$HOME path = " `echo $HOME`
        echo "$SST_CORE_HOME path = " `echo $SST_CORE_HOME`
        echo "$SST_CORE_BIN path = " `echo $SST_CORE_BIN`
        echo "***"
        echo "ls HOME "
        ls -lia $HOME
        echo "***"
        echo "ls $HOME/runner "
        ls -lia $HOME/runner
        echo "***"
        echo "ls $HOME/runner/work "
        ls -lia $HOME/runner/work
        echo "***"
        echo "ls $HOME/runner/work/sst-elements "
        ls -lia $HOME/runner/work/sst-elements
        echo "***"
#        echo "ls SST_SOURCE_PATHS "
#        ls -lia $SST_SOURCE_PATHS
#        echo "***"
#        echo "ls SST_ELEMENTS_SOURCE_PATH "
#        ls -lia $SST_ELEMENTS_SOURCE_PATH
#        echo "***"
#        echo "ls SST_CORE_SOURCE_PATH "
#        ls -lia $SST_CORE_SOURCE_PATH
#        echo "***"




#    - name: Install TestTools Module
#      run: |
#        echo "*******************************************"
#        echo "*** INSTALL TESTTOOLS"
#        echo "*******************************************"
#        pip install testtools
#        echo "***"
#
#    - name: Install OpenMPI
#      run: |
#        echo "*******************************************"
#        echo "*** INSTALL OPENMPI"
#        echo "*******************************************"
#        sudo apt-get install -y openmpi-bin
#        echo "***"
#        echo "Trying mpirun = " `which mpirun`
#        echo "mpirun version = " `mpirun --version`
#        echo "***"
#
#    - name: Setup Autotools
#      run: |
#        echo "*******************************************"
#        echo "*** INSTALL AUTOTOOLS"
#        echo "*******************************************"
#        echo "Trying to install libtool"
#        sudo apt-get install -y libtool-bin
#        echo "***"
#        echo "LIBTOOLIZE path = " `echo $LIBTOOLIZE`
#        echo "LIBTOOL path = " `echo $LIBTOOL`
#        echo "LIBTOOLIZE version = " `libtoolize --version`
#        echo "LIBTOOL    version = " `libtool --version`
#        echo "***"
#
#    - name: System Information Dump - Before Build
#      run: |
#        echo "*******************************************"
#        echo "*** SYSTEM INFO DUMP BEFORE BUILD"
#        echo "*******************************************"
#        echo
#        echo "pwd = " `pwd`
#        echo "***"
#        echo "env | sort = "
#        env | sort
#        echo "***"
#
#    - name: Perform Autogen on SST-Core
#      run: |
#        echo "*******************************************"
#        echo "*** RUNNING AUTOGEN ON SST-Core"
#        echo "*******************************************"
#        ./autogen.sh
#        echo "***"
#
#    - name: Perform Configure on SST-Core
#      run: |
#        echo "*******************************************"
#        echo "*** RUNNING CONFIGURE ON SST-Core"
#        echo "*******************************************"
#        ./configure --prefix=$SST_CORE_HOME
#        echo "***"
#
#    - name: Perform Make on SST-Core
#      run: |
#        echo "*******************************************"
#        echo "*** RUNNING MAKE ON SST-Core"
#        echo "*******************************************"
#        make -j16
#        echo "***"
#
#    - name: Perform Make Install on SST-Core
#      run: |
#        echo "*******************************************"
#        echo "*** RUNNING MAKE INSTALL ON SST-Core"
#        echo "*******************************************"
#        make install
#
#    - name: Check Installation Dirs and Set PATH Env Var
#      run: |
#        echo "*******************************************"
#        echo "*** CHECK INSTALL DIRS AND SET PATH"
#        echo "*******************************************"
#        echo "$HOME path = " `echo $HOME`
#        echo "$SST_CORE_HOME path = " `echo $SST_CORE_HOME`
#        echo "$SST_CORE_BIN path = " `echo $SST_CORE_BIN`
#        echo "***"
#        echo "ls $HOME "
#        ls -lia $HOME
#        echo "***"
#        echo "ls $HOME/local "
#        ls -lia $HOME/local
#        echo "***"
#        echo "ls $SST_CORE_HOME"
#        ls -lia $SST_CORE_HOME
#        echo "***"
#        echo "ls $SST_CORE_BIN"
#        ls -lia $SST_CORE_BIN
#        echo "***"
#        echo "SET THE PATH TO SST BIN DIR (ONLY AVAILABLE IN FUTURE STEPS)"
#        echo $SST_CORE_BIN >> $GITHUB_PATH
#        echo "***"
#        echo "LOCATION OF GITHUB_PATH SCRIPT"
#        echo $GITHUB_PATH
#        echo "***"
#        echo "CONTENTS OF GITHUB_PATH"
#        cat $GITHUB_PATH
#        echo "***"
#
#    - name: Quick Check of SST-Core Operation
#      run: |
#        echo "*******************************************"
#        echo "*** QUICK CHECK OF SST-CORE OPERATION"
#        echo "*******************************************"
#        echo "cd to $HOME"
#        cd $HOME
#        echo "***"
#        echo "RUNNING SST FROM HOME DIR"
#        echo "sst version = " `$SST_CORE_BIN/sst --version`
#        echo "***"
#        echo "RUNNING SST --VERSION USING THE PATH"
#        sst --version
#        echo "***"
#
#    - name: Perform Testing on SST-Core
#      run: |
#        echo "*******************************************"
#        echo "*** Testing SST-Core"
#        echo "*******************************************"
#        echo "cd to $HOME"
#        cd $HOME
#        echo "***"
#        $SST_CORE_BIN/sst-test-core
#        echo "***"
#        echo "ls $HOME "
#        ls -lia $HOME
#